name: dev_pydsm
channels:
  - conda-forge
  - cadwr-dms
  - nodefaults
dependencies:
  - python
  - pip
  - ipykernel
  - decorator
  - hdf5
  - h5py
  - pandas
  - xarray
  - pyarrow
  - geopandas
  - networkx
  - dask
  - diskcache
  # viz
  - bokeh
  - matplotlib
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  # custom packages
  - pyhecdss
  - vtools3
  # dev tools
  - black
  - pytest
  - pytest-cov
  - pytest-runner
  - nbsphinx
  - sphinx-autobuild
  - pandoc
  - coverage
  - pytest-cov
  # pip install -e . this package
