name: dev_pydsm
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - h5py=2.10
  - numpy
  - pandas
  - geopandas
  # viz
  - geoviews
  - matplotlib
  - hvplot
  - datashader
  - networkx
  - ipyleaflet
  - ipywidgets
  # custom channels
  - pyhecdss
  - vtools3
  # dev stuff
  - pytest-runner
  - autopep8
  - click
  - nbsphinx
  - sphinx-autobuild
  - coverage
  - pytest-cov

