name: pydsm-docs
channels:
  - conda-forge
  - cadwr-dms
  - nodefaults
dependencies:
  # Core runtime (mirrors environment.yml)
  - python=3.13
  - pip
  - ipykernel
  - decorator
  - hdf5
  - h5py
  - numpy<2
  - pandas
  - xarray
  - pyarrow
  - geopandas
  - networkx
  - dask
  - diskcache
  - tabulate
  # Visualization stack
  - bokeh
  - matplotlib
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  # Custom packages from channel(s)
  - pyhecdss
  - vtools3
  # Documentation specific additions
  - sphinx
  - nbsphinx
  - sphinx-rtd-theme
  - jupyter
  - nbconvert
  - pandoc
  # Optional speed / compilation helpers (leave commented for now)
  # - numba
  - pip:
      - .
