name: pydsm
channels:
  - cadwr-dms
  - pyviz
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - h5py=2.10 # because we use hdf5 v10 or below for DSM2 with szip from custom channel
  - numpy
  - pandas
  - geopandas
  # viz
  - geoviews
  - matplotlib
  - hvplot
  - datashader
  - networkx
  - ipyleaflet
  - ipywidgets
  # custom channels
  - pyhecdss
  - vtools3

