name: pydsm
channels:
  - conda-forge
  - cadwr-dms
  - nodefaults
dependencies:
  - python
  - pip
  - ipykernel
  - decorator
  - hdf5
  - h5py
  - pandas
  - xarray
  - pyarrow
  - geopandas
  - networkx
  - dask
  - diskcache
  # viz
  - bokeh
  - matplotlib
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  # custom packages
  - pyhecdss
  - vtools3
  - pip:
      - -e git+https://github.com/CADWRDeltaModeling/pydsm#egg=pydsm
