name: pydsm
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - ipykernel
  - decorator
  - hdf5=1.14.0  # https://github.com/conda-forge/hdf5-feedstock/issues/207
  - h5py
  - pandas
  - xarray
  - pyarrow
  - geopandas
  - networkx
  # viz
  - matplotlib
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - panel
  # custom packages
  - pyhecdss
  - vtools3
  - pip:
      - -e git+https://github.com/CADWRDeltaModeling/pydsm#egg=pydsm
