name: dev_pydsm
channels:
  - conda-forge
  - pyviz
  - cadwr-dms
  - nodefaults
dependencies:
  - python
  - ipykernel
  - h5py #=2.10 #=2.10
  - hdf5 #=1.10.4
  - numpy #=1.23.5
  - pandas
  - pyarrow
  - cartopy
  - click-plugins
  - cligj
  - munch
  - pyproj
  - pyshp
  - shapely
  # pip install these geo dependencies see at bottom
  - pip
  - geoviews
  - geopandas
  - fiona
  #- pip:
  #  - geopandas
  #  - geoviews
  #  - fiona
  #
  - matplotlib
  - hvplot
  - datashader
  - networkx
  - panel
  - jupyter_bokeh
  # custom channels
  - pyhecdss
  - vtools3
  # dev stuff
  - pytest-runner
  - autopep8
  - click
  - nbsphinx
  - sphinx-autobuild
  - pandoc
  - coverage
  - pytest-cov
# pip install Pillow
# pip install fiona
# pip install jupyter_bokeh