name: pydsm
channels:
  - cadwr-dms
  - conda-forge
  - nodefaults
dependencies:
  - python #=3.
  - pip
  - ipykernel
  - hdf5=1.14.0 # https://github.com/conda-forge/hdf5-feedstock/issues/207
  - h5py #=2.10 # because we use hdf5 v10 or below for DSM2 with szip from custom channel
  - numpy
  - pandas
  - pyarrow
  - geopandas
  # viz
  - geoviews
  - matplotlib
  - hvplot
  - datashader
  - networkx
  - panel
  #- ipyleaflet
  #- ipywidgets
  # custom channels
  - pyhecdss
  - vtools3
  - black
  - pytest
  - pytest-cov
  - pytest-runner
  - nbsphinx
  - sphinx-autobuild
  - pandoc
  - coverage
  - pytest-cov
