start_time: &start_time 2020-01-01 00:00:00 #global begining period of updating dsm2 input dss file
end_time: &end_time 2026-01-01 00:00:00 #global end period of updating dsm2 input dss file
processed_data: &processed //cnrastore-bdo/Modeling_Data/repo/structures/processed/dms_ccfb@radial_height.csv
dss_file: &gate_dss  Z:\dsm2_studies\timeseries\gates.dss

ccf_gate_ele:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  process_ccf_file: *processed
  column_name: height #column name in the processed csv file
  outfile: *gate_dss
  dss_path: //CHWST000/WEIRELEVATION//// #specify the DSS path that can uniquely identify the time series in the DSS file


ccf_ndup:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  process_ccf_file: *processed
  outfile: *gate_dss
  column_name: ndup #column name in the processed csv file
  dss_path: //CHWST000/NDUPLICATE//// #specify the DSS path that can uniquely identify the time series in the DSS file