start_time: &start_time 2020-01-01 00:00:00 #global begining period of updating dsm2 input dss file
end_time: &end_time 2027-01-01 00:00:00 #global end period of updating dsm2 input dss file
ec_bc_dss: &ec_bc_dss Z:\dsm2_studies\timeseries\hist_forQAQC.dss #hist.dss in DSM2 timeseries folder


vernalis:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: vns
  outfile: *ec_bc_dss
  dss_path: //RSAN112/EC//// #specify the DSS path that can uniquely identify the time series in the DSS file
