start_time: &start_time 2020-01-01 00:00:00 #global begining period of updating dsm2 input dss file
end_time: &end_time 2027-01-01 00:00:00 #global end period of updating dsm2 input dss file
dss_file: &gate_dss  Z:\dsm2_studies\timeseries\gates.dss

ccf_gate_ele:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: ccfb
  processed_file: //cnrastore-bdo/Modeling_data/repo/structures/processed/dms_ccfb@radial_height.csv
  column_name: height #column name in the processed csv file
  outfile: *gate_dss
  dss_path: //CHWST000/WEIRELEVATION//// #specify the DSS path that can uniquely identify the time series in the DSS file

ccf_ndup:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: ccfb
  processed_file: //cnrastore-bdo/Modeling_data/repo/structures/processed/dms_ccfb@radial_height.csv
  column_name: ndup #column name in the processed csv file
  outfile: *gate_dss
  dss_path: //CHWST000/NDUPLICATE//// #specify the DSS path that can uniquely identify the time series in the DSS file

dcc:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: dcc
  processed_file: //cnrastore-bdo/Modeling_data/repo/structures/processed/dms_dcc_ops.csv
  outfile: *gate_dss
  column_name: action #column name in the processed csv file
  dss_path: //RSAC128/POS//// #specify the DSS path that can uniquely identify the time series in the DSS file


smscg:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: smscg
  processed_file: //cnrastore-bdo/Modeling_data/repo/structures/processed/dms_smscg_ops.csv
  outfile: *gate_dss
  column_name: [flashboards, gate_1, gate_2, gate_3] #column name in the processed csv file
  dss_path_boatlock: //MTZSL/BOATLOCK_OP//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_flashboard: //MTZSL/FLASHBOARD_OP////
  dss_path_mod_flashboard: //MTZSL/MOD_FLASHBOARD_OP////
  dss_path_radial_op: //MTZSL/RADIAL_OP////
  dss_path_radial_to: //MTZSL/RADIAL_FRACT_DOWN////
  dss_path_radial_from: //MTZSL/RADIAL_FRACT_UP////


glc:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: glc
  processed_file: Z:/DD-311/schism_temporary_barrier_th/grantline_barrier.th
  outfile: *gate_dss
  column_name: [install,elev_weir,width_weir,down_op_pipe]
  dss_path_weir_install: //GL_CN/INSTALL//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_weir_elev: //GL_CN/WEIRELEVATION//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_weir_width: //GL_CN/WEIRWIDTH//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_pipe_op: //GL_CN/PIPE_OP_DOWN//// #specify the DSS path that can uniquely identify the time series in the DSS file


mid_r:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: mid_r
  outfile: *gate_dss
  column_name: [install,elev,op_down] #column name in the processed csv file
  processed_file1: Z:/DD-311/schism_temporary_barrier_th/midr_weir.th
  processed_file2: Z:/DD-311/schism_temporary_barrier_th/midr_culvert_l.th
  processed_file3: Z:/DD-311/schism_temporary_barrier_th/midr_culvert_r.th
  dss_path_install: //MID_R/INSTALL//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_elev: //MID_R/WEIRELEVATION//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_op_down: //MID_R/PIPE_OP_DOWN//// #specify the DSS path that can uniquely identify the time series in the DSS file


old_r_tracy:
  start: *start_time #individual begining period of updating data
  end: *end_time #individual end period of updating data
  station_id: old_r_tracy
  outfile: *gate_dss
  column_name: [install,op_down_weir] #column name in the processed csv file
  processed_file: Z:/DD-311/schism_temporary_barrier_th/oldr_tracy_barrier.th
  dss_path_install: //OLD_R/INSTALL//// #specify the DSS path that can uniquely identify the time series in the DSS file
  dss_path_op_down: //OLD_R/PIPE_OP_DOWN//// #specify the DSS path that can uniquely identify the time series in the DSS file