{% set name = "pydsm" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/pydsm.git
  path: ..

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pydsm = pydsm.cli:main
  #skip:           true

requirements:
  build:
    - python {{ python }}
    - setuptools
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - {{ pin_compatible('python', lower_bound='3.5', upper_bound='4.0') }}
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  test:
    imports:
      - pydsm
    source_files:
      - tests
    requires:
      - pytest
      - pytest-cov
    commands:
      - (setlocal && cd tests && pytest && endlocal) # [win]
      - (cd tests; pytest) # [unix]

about:
  home:           "https://github.com/CADWRDeltaModeling/pydsm"
  license:        "MIT"
  license_family: "MIT"
  summary:        "python interface to DSM2 related functionality"
