{% set name = "pydsm" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/pydsm.git
  path: ..

build:
  number: 0
  noarch: python
  #skip:           true

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.23
    - click >=6.0
  run:
    - python
    - numpy  >=1.11
    - pandas >=0.23
    - click >=6.0
  test:
    imports:
      - pydsm

about:
  home:           "https://github.com/CADWRDeltaModeling/pydsm"
  license:        "MIT"
  license_family: "MIT"
  summary:        "python interface to DSM2 related functionality"
