{% set name = "pydsm" %}
{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject['project'] %}

package:
  name:           "{{ name|lower }}"
  version: {{ SETUPTOOLS_SCM_PRETEND_VERSION }}

source:
  #git_url: https://github.com/CADWRDeltaModeling/pydsm.git
  path: ..

build:
  number: 0
  noarch: python
  script_env:
   - SETUPTOOLS_SCM_PRETEND_VERSION
  script: {{ PYTHON }} -m pip install --no-build-isolation --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  entry_points:
    {% for name, reference in project['scripts'].items() %}
    - {{ name }} = {{ reference }}
    {% endfor %}
  #skip:           true

requirements:
  host:
    - python {{ project['requires-python'] }}
    - pip
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - {{ pin_compatible('python', lower_bound='3.5', upper_bound='4.0') }}
    {% for dep in project.get('dependencies', []) %}
    - {{ dep.lower() }}
    {% endfor %}  
  test:
    imports:
      - pydsm
    source_files:
      - tests
    requires:
      - pytest
      - pytest-cov
    {% for dep in project.get("optional-dependencies", {}).get('test', []) %}
    - {{ dep.lower() }}
    {% endfor %}
    commands:
      - (setlocal && cd tests && pytest && endlocal) # [win]
      - (cd tests; pytest) # [unix]

about:
  home:           "https://github.com/CADWRDeltaModeling/pydsm"
  license:        "MIT"
  license_family: "MIT"
  summary:        "python interface to DSM2 related functionality"
