{% set name = "pydsm" %}
{% set data = load_setup_py_data() %}

package:
  name:           "{{ name|lower }}"
  version:        "{{ data['version'] }}"

source:
  #git_url: https://github.com/CADWRDeltaModeling/pydsm.git
  path: ..

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pydsm = pydsm.cli:main
  #skip:           true

requirements:
  build:
    - python
    - setuptools
    - pandas >=0.23
    - click >=6.0
    - pytest-runner >=5.0
  run:
    - python
    - numpy  >=1.11
    - pandas >=0.23
    - click >=6.0
  test:
    imports:
      - pydsm
    source_files:
      - tests
    requires:
      - pytest
      - pytest-cov
    commands:
      - (setlocal && cd tests && pytest && endlocal) # [win]
      - (cd tests; pytest) # [unix]

about:
  home:           "https://github.com/CADWRDeltaModeling/pydsm"
  license:        "MIT"
  license_family: "MIT"
  summary:        "python interface to DSM2 related functionality"
