name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-docs.yml
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=3.13
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
              - cadwr-dms
              - nodefaults
            channel_priority: flexible

      - name: Show environment details
        run: |
          micromamba info
          micromamba list
          python --version
          which python
          which sphinx-build || true

      - name: Verify docs tooling imports
        run: |
          python -c "import importlib, sphinx, nbsphinx; print('sphinx', sphinx.__version__); print('nbsphinx', nbsphinx.__version__); [importlib.import_module(m) for m in ['pydsm','networkx','pandas','h5py']]; print('Imports OK')"

      - name: Build HTML docs
        working-directory: docsrc
        env:
          NBSPHINX_ALLOW_ERRORS: "0"
        run: |
          sphinx-build -b html -W --keep-going . _build/html
          echo "Built docs size:" && du -sh _build/html || true

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docsrc/_build/html
          if-no-files-found: error
          retention-days: 7

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download built docs
        uses: actions/download-artifact@v4
        with:
          name: docs-html
          path: ./site

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
