name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Conda build package and upload to anaconda.org
      env:
        ANACONDA_CHANNEL_UPLOAD_TOKEN: ${{ secrets.ANACONDA_CHANNEL_UPLOAD_TOKEN }}
      run: |
        conda create -n test_pydsm -y conda-build conda-verify numpy anaconda-client
        source $CONDA/etc/profile.d/conda.sh
        conda activate test_pydsm
        conda config --set anaconda_upload yes
        conda build -c conda-forge -c cadwr-dms -c defaults --user cadwr-dms --token "$ANACONDA_CHANNEL_UPLOAD_TOKEN" conda.recipe
        conda activate
        conda remove -n test_pydsm --all
