name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Conda build package and upload to anaconda.org
      env:
        ANACONDA_CHANNEL_UPLOAD_TOKEN: ${{ secrets.ANACONDA_CHANNEL_UPLOAD_TOKEN }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install -n base -y conda-build anaconda-client setuptools_scm
        conda config --set anaconda_upload yes
        export SETUPTOOLS_SCM_PRETEND_VERSION=$(python -m setuptools_scm)
        conda build -c conda-forge -c cadwr-dms -c defaults --user cadwr-dms --token "$ANACONDA_CHANNEL_UPLOAD_TOKEN" conda.recipe
